=== instrumenta/kubernetes-json-schema/v1.10.11-local/jsonschemaprops.json
{
  "$schema": "http://json-schema.org/schema#", 
  "type": "object", 
  "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).", 
  "properties": {
    "minProperties": {
      "type": "integer", 
      "format": "int64"
    }, 
    "uniqueItems": {
      "type": "boolean"
    }, 
    "minimum": {
      "type": "number", 
      "format": "double"
    }, 
    "maxItems": {
      "type": "integer", 
      "format": "int64"
    }, 
    "$schema": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "anyOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "id": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "$ref": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "exclusiveMaximum": {
      "type": "boolean"
    }, 
    "title": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "exclusiveMinimum": {
      "type": "boolean"
    }, 
    "allOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "patternProperties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "multipleOf": {
      "type": "number", 
      "format": "double"
    }, 
    "maxProperties": {
      "type": "integer", 
      "format": "int64"
    }, 
    "type": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "description": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "format": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "minLength": {
      "type": "integer", 
      "format": "int64"
    }, 
    "enum": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "oneOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "dependencies": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrStringArray"
      }, 
      "type": "object"
    }, 
    "maxLength": {
      "type": "integer", 
      "format": "int64"
    }, 
    "not": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
    }, 
    "externalDocs": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.ExternalDocumentation"
    }, 
    "properties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "additionalItems": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    }, 
    "default": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    }, 
    "items": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray"
    }, 
    "required": {
      "items": {
        "type": "string"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "maximum": {
      "type": "number", 
      "format": "double"
    }, 
    "minItems": {
      "type": "integer", 
      "format": "int64"
    }, 
    "pattern": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "additionalProperties": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    }, 
    "definitions": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "example": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    }
  }
}

=== instrumenta/kubernetes-json-schema/v1.19.3-local/podsecuritypolicyspec-policy-v1beta1.json
{
  "description": "PodSecurityPolicySpec defines the policy enforced.",
  "properties": {
    "allowPrivilegeEscalation": {
      "description": "allowPrivilegeEscalation determines if a pod can request to allow privilege escalation. If unspecified, defaults to true.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "allowedCSIDrivers": {
      "description": "AllowedCSIDrivers is an allowlist of inline CSI drivers that must be explicitly set to be embedded within a pod spec. An empty value indicates that any CSI driver can be used for inline ephemeral volumes. This is a beta field, and is only honored if the API server enables the CSIInlineVolume feature gate.",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.AllowedCSIDriver"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "allowedCapabilities": {
      "description": "allowedCapabilities is a list of capabilities that can be requested to add to the container. Capabilities in this field may be added at the pod author's discretion. You must not list a capability in both allowedCapabilities and requiredDropCapabilities.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    },
    "allowedFlexVolumes": {
      "description": "allowedFlexVolumes is an allowlist of Flexvolumes.  Empty or nil indicates that all Flexvolumes may be used.  This parameter is effective only when the usage of the Flexvolumes is allowed in the \"volumes\" field.",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.AllowedFlexVolume"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "allowedHostPaths": {
      "description": "allowedHostPaths is an allowlist of host paths. Empty indicates that all host paths may be used.",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.AllowedHostPath"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "allowedProcMountTypes": {
      "description": "AllowedProcMountTypes is an allowlist of allowed ProcMountTypes. Empty or nil indicates that only the DefaultProcMountType may be used. This requires the ProcMountType feature flag to be enabled.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    },
    "allowedUnsafeSysctls": {
      "description": "allowedUnsafeSysctls is a list of explicitly allowed unsafe sysctls, defaults to none. Each entry is either a plain sysctl name or ends in \"*\" in which case it is considered as a prefix of allowed sysctls. Single * means all unsafe sysctls are allowed. Kubelet has to allowlist all allowed unsafe sysctls explicitly to avoid rejection.\n\nExamples: e.g. \"foo/*\" allows \"foo/bar\", \"foo/baz\", etc. e.g. \"foo.*\" allows \"foo.bar\", \"foo.baz\", etc.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    },
    "defaultAddCapabilities": {
      "description": "defaultAddCapabilities is the default set of capabilities that will be added to the container unless the pod spec specifically drops the capability.  You may not list a capability in both defaultAddCapabilities and requiredDropCapabilities. Capabilities added here are implicitly allowed, and need not be included in the allowedCapabilities list.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    },
    "defaultAllowPrivilegeEscalation": {
      "description": "defaultAllowPrivilegeEscalation controls the default setting for whether a process can gain more privileges than its parent process.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "forbiddenSysctls": {
      "description": "forbiddenSysctls is a list of explicitly forbidden sysctls, defaults to none. Each entry is either a plain sysctl name or ends in \"*\" in which case it is considered as a prefix of forbidden sysctls. Single * means all sysctls are forbidden.\n\nExamples: e.g. \"foo/*\" forbids \"foo/bar\", \"foo/baz\", etc. e.g. \"foo.*\" forbids \"foo.bar\", \"foo.baz\", etc.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    },
    "fsGroup": {
      "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.FSGroupStrategyOptions",
      "description": "fsGroup is the strategy that will dictate what fs group is used by the SecurityContext."
    },
    "hostIPC": {
      "description": "hostIPC determines if the policy allows the use of HostIPC in the pod spec.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "hostNetwork": {
      "description": "hostNetwork determines if the policy allows the use of HostNetwork in the pod spec.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "hostPID": {
      "description": "hostPID determines if the policy allows the use of HostPID in the pod spec.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "hostPorts": {
      "description": "hostPorts determines which host port ranges are allowed to be exposed.",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.HostPortRange"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "privileged": {
      "description": "privileged determines if a pod can request to be run as privileged.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "readOnlyRootFilesystem": {
      "description": "readOnlyRootFilesystem when set to true will force containers to run with a read only root file system.  If the container specifically requests to run with a non-read only root file system the PSP should deny the pod. If set to false the container may run with a read only root file system if it wishes but it will not be forced to.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "requiredDropCapabilities": {
      "description": "requiredDropCapabilities are the capabilities that will be dropped from the container.  These are required to be dropped and cannot be added.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    },
    "runAsGroup": {
      "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.RunAsGroupStrategyOptions",
      "description": "RunAsGroup is the strategy that will dictate the allowable RunAsGroup values that may be set. If this field is omitted, the pod's RunAsGroup can take any value. This field requires the RunAsGroup feature gate to be enabled."
    },
    "runAsUser": {
      "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.RunAsUserStrategyOptions",
      "description": "runAsUser is the strategy that will dictate the allowable RunAsUser values that may be set."
    },
    "runtimeClass": {
      "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.RuntimeClassStrategyOptions",
      "description": "runtimeClass is the strategy that will dictate the allowable RuntimeClasses for a pod. If this field is omitted, the pod's runtimeClassName field is unrestricted. Enforcement of this field depends on the RuntimeClass feature gate being enabled."
    },
    "seLinux": {
      "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.SELinuxStrategyOptions",
      "description": "seLinux is the strategy that will dictate the allowable labels that may be set."
    },
    "supplementalGroups": {
      "$ref": "_definitions.json#/definitions/io.k8s.api.policy.v1beta1.SupplementalGroupsStrategyOptions",
      "description": "supplementalGroups is the strategy that will dictate what supplemental groups are used by the SecurityContext."
    },
    "volumes": {
      "description": "volumes is an allowlist of volume plugins. Empty indicates that no volumes may be used. To allow all volumes you may use '*'.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    }
  },
  "required": [
    "seLinux",
    "runAsUser",
    "supplementalGroups",
    "fsGroup"
  ],
  "type": "object",
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/v1.12.1-standalone-strict/flexvolumesource.json
{
  "additionalProperties": false, 
  "required": [
    "driver"
  ], 
  "description": "FlexVolume represents a generic volume resource that is provisioned/attached using an exec based plugin.", 
  "properties": {
    "secretRef": {
      "additionalProperties": false, 
      "description": "LocalObjectReference contains enough information to let you locate the referenced object inside the same namespace.", 
      "properties": {
        "name": {
          "type": [
            "string", 
            "null"
          ], 
          "description": "Name of the referent. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names"
        }
      }
    }, 
    "fsType": {
      "type": [
        "string", 
        "null"
      ], 
      "description": "Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\". The default filesystem depends on FlexVolume script."
    }, 
    "driver": {
      "type": [
        "string", 
        "null"
      ], 
      "description": "Driver is the name of the driver to use for this volume."
    }, 
    "readOnly": {
      "type": "boolean", 
      "description": "Optional: Defaults to false (read/write). ReadOnly here will force the ReadOnly setting in VolumeMounts."
    }, 
    "options": {
      "additionalProperties": {
        "type": [
          "string", 
          "null"
        ]
      }, 
      "type": "object", 
      "description": "Optional: Extra command options if any."
    }
  }
}

=== instrumenta/kubernetes-json-schema/v1.16.7-standalone-strict/containerstate-v1.json
{
  "description": "ContainerState holds a possible state of container. Only one of its members may be specified. If none of them is specified, the default one is ContainerStateWaiting.",
  "properties": {
    "running": {
      "description": "ContainerStateRunning is a running state of a container.",
      "properties": {
        "startedAt": {
          "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
          "format": "date-time",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    },
    "terminated": {
      "description": "ContainerStateTerminated is a terminated state of a container.",
      "properties": {
        "containerID": {
          "description": "Container's ID in the format 'docker://<container_id>'",
          "type": [
            "string",
            "null"
          ]
        },
        "exitCode": {
          "description": "Exit status from the last termination of the container",
          "format": "int32",
          "type": "integer"
        },
        "finishedAt": {
          "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
          "format": "date-time",
          "type": [
            "string",
            "null"
          ]
        },
        "message": {
          "description": "Message regarding the last termination of the container",
          "type": [
            "string",
            "null"
          ]
        },
        "reason": {
          "description": "(brief) reason from the last termination of the container",
          "type": [
            "string",
            "null"
          ]
        },
        "signal": {
          "description": "Signal from the last termination of the container",
          "format": "int32",
          "type": [
            "integer",
            "null"
          ]
        },
        "startedAt": {
          "description": "Time is a wrapper around time.Time which supports correct marshaling to YAML and JSON.  Wrappers are provided for many of the factory methods that the time package offers.",
          "format": "date-time",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "required": [
        "exitCode"
      ],
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    },
    "waiting": {
      "description": "ContainerStateWaiting is a waiting state of a container.",
      "properties": {
        "message": {
          "description": "Message regarding why the container is not yet running.",
          "type": [
            "string",
            "null"
          ]
        },
        "reason": {
          "description": "(brief) reason the container is not yet running.",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/v1.18.1-standalone-strict/horizontalpodautoscalerbehavior-autoscaling-v2beta2.json
{
  "description": "HorizontalPodAutoscalerBehavior configures the scaling behavior of the target in both Up and Down directions (scaleUp and scaleDown fields respectively).",
  "properties": {
    "scaleDown": {
      "description": "HPAScalingRules configures the scaling behavior for one direction. These Rules are applied after calculating DesiredReplicas from metrics for the HPA. They can limit the scaling velocity by specifying scaling policies. They can prevent flapping by specifying the stabilization window, so that the number of replicas is not set instantly, instead, the safest value from the stabilization window is chosen.",
      "properties": {
        "policies": {
          "description": "policies is a list of potential scaling polices which can be used during scaling. At least one policy must be specified, otherwise the HPAScalingRules will be discarded as invalid",
          "items": {
            "description": "HPAScalingPolicy is a single policy which must hold true for a specified past interval.",
            "properties": {
              "periodSeconds": {
                "description": "PeriodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).",
                "format": "int32",
                "type": "integer"
              },
              "type": {
                "description": "Type is used to specify the scaling policy.",
                "type": "string"
              },
              "value": {
                "description": "Value contains the amount of change which is permitted by the policy. It must be greater than zero",
                "format": "int32",
                "type": "integer"
              }
            },
            "required": [
              "type",
              "value",
              "periodSeconds"
            ],
            "type": [
              "object",
              "null"
            ],
            "additionalProperties": false
          },
          "type": [
            "array",
            "null"
          ]
        },
        "selectPolicy": {
          "description": "selectPolicy is used to specify which policy should be used. If not set, the default value MaxPolicySelect is used.",
          "type": [
            "string",
            "null"
          ]
        },
        "stabilizationWindowSeconds": {
          "description": "StabilizationWindowSeconds is the number of seconds for which past recommendations should be considered while scaling up or scaling down. StabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour). If not set, use the default values: - For scale up: 0 (i.e. no stabilization is done). - For scale down: 300 (i.e. the stabilization window is 300 seconds long).",
          "format": "int32",
          "type": [
            "integer",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    },
    "scaleUp": {
      "description": "HPAScalingRules configures the scaling behavior for one direction. These Rules are applied after calculating DesiredReplicas from metrics for the HPA. They can limit the scaling velocity by specifying scaling policies. They can prevent flapping by specifying the stabilization window, so that the number of replicas is not set instantly, instead, the safest value from the stabilization window is chosen.",
      "properties": {
        "policies": {
          "description": "policies is a list of potential scaling polices which can be used during scaling. At least one policy must be specified, otherwise the HPAScalingRules will be discarded as invalid",
          "items": {
            "description": "HPAScalingPolicy is a single policy which must hold true for a specified past interval.",
            "properties": {
              "periodSeconds": {
                "description": "PeriodSeconds specifies the window of time for which the policy should hold true. PeriodSeconds must be greater than zero and less than or equal to 1800 (30 min).",
                "format": "int32",
                "type": "integer"
              },
              "type": {
                "description": "Type is used to specify the scaling policy.",
                "type": "string"
              },
              "value": {
                "description": "Value contains the amount of change which is permitted by the policy. It must be greater than zero",
                "format": "int32",
                "type": "integer"
              }
            },
            "required": [
              "type",
              "value",
              "periodSeconds"
            ],
            "type": [
              "object",
              "null"
            ],
            "additionalProperties": false
          },
          "type": [
            "array",
            "null"
          ]
        },
        "selectPolicy": {
          "description": "selectPolicy is used to specify which policy should be used. If not set, the default value MaxPolicySelect is used.",
          "type": [
            "string",
            "null"
          ]
        },
        "stabilizationWindowSeconds": {
          "description": "StabilizationWindowSeconds is the number of seconds for which past recommendations should be considered while scaling up or scaling down. StabilizationWindowSeconds must be greater than or equal to zero and less than or equal to 3600 (one hour). If not set, use the default values: - For scale up: 0 (i.e. no stabilization is done). - For scale down: 300 (i.e. the stabilization window is 300 seconds long).",
          "format": "int32",
          "type": [
            "integer",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}
