=== instrumenta/kubernetes-json-schema/v1.10.11-local/jsonschemaprops.json
{
  "$schema": "http://json-schema.org/schema#", 
  "type": "object", 
  "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).", 
  "properties": {
    "minProperties": {
      "type": "integer", 
      "format": "int64"
    }, 
    "uniqueItems": {
      "type": "boolean"
    }, 
    "minimum": {
      "type": "number", 
      "format": "double"
    }, 
    "maxItems": {
      "type": "integer", 
      "format": "int64"
    }, 
    "$schema": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "anyOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "id": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "$ref": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "exclusiveMaximum": {
      "type": "boolean"
    }, 
    "title": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "exclusiveMinimum": {
      "type": "boolean"
    }, 
    "allOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "patternProperties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "multipleOf": {
      "type": "number", 
      "format": "double"
    }, 
    "maxProperties": {
      "type": "integer", 
      "format": "int64"
    }, 
    "type": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "description": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "format": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "minLength": {
      "type": "integer", 
      "format": "int64"
    }, 
    "enum": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "oneOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "dependencies": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrStringArray"
      }, 
      "type": "object"
    }, 
    "maxLength": {
      "type": "integer", 
      "format": "int64"
    }, 
    "not": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
    }, 
    "externalDocs": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.ExternalDocumentation"
    }, 
    "properties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "additionalItems": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    }, 
    "default": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    }, 
    "items": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray"
    }, 
    "required": {
      "items": {
        "type": "string"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "maximum": {
      "type": "number", 
      "format": "double"
    }, 
    "minItems": {
      "type": "integer", 
      "format": "int64"
    }, 
    "pattern": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "additionalProperties": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    }, 
    "definitions": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "example": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    }
  }
}

=== instrumenta/kubernetes-json-schema/v1.16.8-standalone-strict/customresourceconversion-apiextensions-v1.json
{
  "description": "CustomResourceConversion describes how to convert different versions of a CR.",
  "properties": {
    "strategy": {
      "description": "strategy specifies how custom resources are converted between versions. Allowed values are: - `None`: The converter only change the apiVersion and would not touch any other field in the custom resource. - `Webhook`: API Server will call to an external webhook to do the conversion. Additional information\n  is needed for this option. This requires spec.preserveUnknownFields to be false, and spec.conversion.webhook to be set.",
      "type": [
        "string",
        "null"
      ]
    },
    "webhook": {
      "description": "WebhookConversion describes how to call a conversion webhook",
      "properties": {
        "clientConfig": {
          "description": "WebhookClientConfig contains the information to make a TLS connection with the webhook.",
          "properties": {
            "caBundle": {
              "description": "caBundle is a PEM encoded CA bundle which will be used to validate the webhook's server certificate. If unspecified, system trust roots on the apiserver are used.",
              "format": "byte",
              "type": [
                "string",
                "null"
              ]
            },
            "service": {
              "description": "ServiceReference holds a reference to Service.legacy.k8s.io",
              "properties": {
                "name": {
                  "description": "name is the name of the service. Required",
                  "type": "string"
                },
                "namespace": {
                  "description": "namespace is the namespace of the service. Required",
                  "type": "string"
                },
                "path": {
                  "description": "path is an optional URL path at which the webhook will be contacted.",
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "port": {
                  "description": "port is an optional service port at which the webhook will be contacted. `port` should be a valid port number (1-65535, inclusive). Defaults to 443 for backward compatibility.",
                  "format": "int32",
                  "type": [
                    "integer",
                    "null"
                  ]
                }
              },
              "required": [
                "namespace",
                "name"
              ],
              "type": [
                "object",
                "null"
              ],
              "additionalProperties": false
            },
            "url": {
              "description": "url gives the location of the webhook, in standard URL form (`scheme://host:port/path`). Exactly one of `url` or `service` must be specified.\n\nThe `host` should not refer to a service running in the cluster; use the `service` field instead. The host might be resolved via external DNS in some apiservers (e.g., `kube-apiserver` cannot resolve in-cluster DNS as that would be a layering violation). `host` may also be an IP address.\n\nPlease note that using `localhost` or `127.0.0.1` as a `host` is risky unless you take great care to run this webhook on all hosts which run an apiserver which might need to make calls to this webhook. Such installs are likely to be non-portable, i.e., not easy to turn up in a new cluster.\n\nThe scheme must be \"https\"; the URL must begin with \"https://\".\n\nA path is optional, and if present may be any string permissible in a URL. You may use the path to pass an arbitrary string to the webhook, for example, a cluster identifier.\n\nAttempting to use a user or basic auth e.g. \"user:password@\" is not allowed. Fragments (\"#...\") and query parameters (\"?...\") are not allowed, either.",
              "type": [
                "string",
                "null"
              ]
            }
          },
          "type": [
            "object",
            "null"
          ],
          "additionalProperties": false
        },
        "conversionReviewVersions": {
          "description": "conversionReviewVersions is an ordered list of preferred `ConversionReview` versions the Webhook expects. The API server will use the first version in the list which it supports. If none of the versions specified in this list are supported by API server, conversion will fail for the custom resource. If a persisted Webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail.",
          "items": {
            "type": [
              "string",
              "null"
            ]
          },
          "type": "array"
        }
      },
      "required": [
        "conversionReviewVersions"
      ],
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    }
  },
  "required": [
    "strategy"
  ],
  "type": "object",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/v1.16.5-standalone-strict/securitycontext-v1.json
{
  "description": "SecurityContext holds security configuration that will be applied to a container. Some fields are present in both SecurityContext and PodSecurityContext.  When both are set, the values in SecurityContext take precedence.",
  "properties": {
    "allowPrivilegeEscalation": {
      "description": "AllowPrivilegeEscalation controls whether a process can gain more privileges than its parent process. This bool directly controls if the no_new_privs flag will be set on the container process. AllowPrivilegeEscalation is true always when the container is: 1) run as Privileged 2) has CAP_SYS_ADMIN",
      "type": [
        "boolean",
        "null"
      ]
    },
    "capabilities": {
      "description": "Adds and removes POSIX capabilities from running containers.",
      "properties": {
        "add": {
          "description": "Added capabilities",
          "items": {
            "type": [
              "string",
              "null"
            ]
          },
          "type": [
            "array",
            "null"
          ]
        },
        "drop": {
          "description": "Removed capabilities",
          "items": {
            "type": [
              "string",
              "null"
            ]
          },
          "type": [
            "array",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    },
    "privileged": {
      "description": "Run container in privileged mode. Processes in privileged containers are essentially equivalent to root on the host. Defaults to false.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "procMount": {
      "description": "procMount denotes the type of proc mount to use for the containers. The default is DefaultProcMount which uses the container runtime defaults for readonly paths and masked paths. This requires the ProcMountType feature flag to be enabled.",
      "type": [
        "string",
        "null"
      ]
    },
    "readOnlyRootFilesystem": {
      "description": "Whether this container has a read-only root filesystem. Default is false.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "runAsGroup": {
      "description": "The GID to run the entrypoint of the container process. Uses runtime default if unset. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.",
      "format": "int64",
      "type": [
        "integer",
        "null"
      ]
    },
    "runAsNonRoot": {
      "description": "Indicates that the container must run as a non-root user. If true, the Kubelet will validate the image at runtime to ensure that it does not run as UID 0 (root) and fail to start the container if it does. If unset or false, no such validation will be performed. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.",
      "type": [
        "boolean",
        "null"
      ]
    },
    "runAsUser": {
      "description": "The UID to run the entrypoint of the container process. Defaults to user specified in image metadata if unspecified. May also be set in PodSecurityContext.  If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence.",
      "format": "int64",
      "type": [
        "integer",
        "null"
      ]
    },
    "seLinuxOptions": {
      "description": "SELinuxOptions are the labels to be applied to the container",
      "properties": {
        "level": {
          "description": "Level is SELinux level label that applies to the container.",
          "type": [
            "string",
            "null"
          ]
        },
        "role": {
          "description": "Role is a SELinux role label that applies to the container.",
          "type": [
            "string",
            "null"
          ]
        },
        "type": {
          "description": "Type is a SELinux type label that applies to the container.",
          "type": [
            "string",
            "null"
          ]
        },
        "user": {
          "description": "User is a SELinux user label that applies to the container.",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    },
    "windowsOptions": {
      "description": "WindowsSecurityContextOptions contain Windows-specific options and credentials.",
      "properties": {
        "gmsaCredentialSpec": {
          "description": "GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field. This field is alpha-level and is only honored by servers that enable the WindowsGMSA feature flag.",
          "type": [
            "string",
            "null"
          ]
        },
        "gmsaCredentialSpecName": {
          "description": "GMSACredentialSpecName is the name of the GMSA credential spec to use. This field is alpha-level and is only honored by servers that enable the WindowsGMSA feature flag.",
          "type": [
            "string",
            "null"
          ]
        },
        "runAsUserName": {
          "description": "The UserName in Windows to run the entrypoint of the container process. Defaults to the user specified in image metadata if unspecified. May also be set in PodSecurityContext. If set in both SecurityContext and PodSecurityContext, the value specified in SecurityContext takes precedence. This field is alpha-level and it is only honored by servers that enable the WindowsRunAsUserName feature flag.",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    }
  },
  "type": "object",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/v1.14.2-local/webhook-admissionregistration-v1beta1.json
{
  "description": "Webhook describes an admission webhook and the resources and operations it applies to.",
  "properties": {
    "admissionReviewVersions": {
      "description": "AdmissionReviewVersions is an ordered list of preferred `AdmissionReview` versions the Webhook expects. API server will try to use first version in the list which it supports. If none of the versions specified in this list supported by API server, validation will fail for this object. If a persisted webhook configuration specifies allowed versions and does not include any versions known to the API Server, calls to the webhook will fail and be subject to the failure policy. Default to `['v1beta1']`.",
      "items": {
        "type": [
          "string",
          "null"
        ]
      },
      "type": [
        "array",
        "null"
      ]
    },
    "clientConfig": {
      "$ref": "_definitions.json#/definitions/io.k8s.api.admissionregistration.v1beta1.WebhookClientConfig",
      "description": "ClientConfig defines how to communicate with the hook. Required"
    },
    "failurePolicy": {
      "description": "FailurePolicy defines how unrecognized errors from the admission endpoint are handled - allowed values are Ignore or Fail. Defaults to Ignore.",
      "type": [
        "string",
        "null"
      ]
    },
    "name": {
      "description": "The name of the admission webhook. Name should be fully qualified, e.g., imagepolicy.kubernetes.io, where \"imagepolicy\" is the name of the webhook, and kubernetes.io is the name of the organization. Required.",
      "type": [
        "string",
        "null"
      ]
    },
    "namespaceSelector": {
      "$ref": "_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector",
      "description": "NamespaceSelector decides whether to run the webhook on an object based on whether the namespace for that object matches the selector. If the object itself is a namespace, the matching is performed on object.metadata.labels. If the object is another cluster scoped resource, it never skips the webhook.\n\nFor example, to run the webhook on any objects whose namespace is not associated with \"runlevel\" of \"0\" or \"1\";  you will set the selector as follows: \"namespaceSelector\": {\n  \"matchExpressions\": [\n    {\n      \"key\": \"runlevel\",\n      \"operator\": \"NotIn\",\n      \"values\": [\n        \"0\",\n        \"1\"\n      ]\n    }\n  ]\n}\n\nIf instead you want to only run the webhook on any objects whose namespace is associated with the \"environment\" of \"prod\" or \"staging\"; you will set the selector as follows: \"namespaceSelector\": {\n  \"matchExpressions\": [\n    {\n      \"key\": \"environment\",\n      \"operator\": \"In\",\n      \"values\": [\n        \"prod\",\n        \"staging\"\n      ]\n    }\n  ]\n}\n\nSee https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/ for more examples of label selectors.\n\nDefault to the empty LabelSelector, which matches everything."
    },
    "rules": {
      "description": "Rules describes what operations on what resources/subresources the webhook cares about. The webhook cares about an operation if it matches _any_ Rule. However, in order to prevent ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks from putting the cluster in a state which cannot be recovered from without completely disabling the plugin, ValidatingAdmissionWebhooks and MutatingAdmissionWebhooks are never called on admission requests for ValidatingWebhookConfiguration and MutatingWebhookConfiguration objects.",
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.api.admissionregistration.v1beta1.RuleWithOperations"
      },
      "type": [
        "array",
        "null"
      ]
    },
    "sideEffects": {
      "description": "SideEffects states whether this webhookk has side effects. Acceptable values are: Unknown, None, Some, NoneOnDryRun Webhooks with side effects MUST implement a reconciliation system, since a request may be rejected by a future step in the admission change and the side effects therefore need to be undone. Requests with the dryRun attribute will be auto-rejected if they match a webhook with sideEffects == Unknown or Some. Defaults to Unknown.",
      "type": [
        "string",
        "null"
      ]
    },
    "timeoutSeconds": {
      "description": "TimeoutSeconds specifies the timeout for this webhook. After the timeout passes, the webhook call will be ignored or the API call will fail based on the failure policy. The timeout value must be between 1 and 30 seconds. Default to 30 seconds.",
      "format": "int32",
      "type": [
        "integer",
        "null"
      ]
    }
  },
  "required": [
    "name",
    "clientConfig"
  ],
  "type": "object",
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/v1.10.11-standalone-strict/nodeselectorrequirement.json
{
  "additionalProperties": false, 
  "required": [
    "key", 
    "operator"
  ], 
  "description": "A node selector requirement is a selector that contains values, a key, and an operator that relates the key and values.", 
  "properties": {
    "operator": {
      "type": "string", 
      "description": "Represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists, DoesNotExist. Gt, and Lt."
    }, 
    "values": {
      "items": {
        "type": "string"
      }, 
      "type": "array", 
      "description": "An array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. If the operator is Gt or Lt, the values array must have a single element, which will be interpreted as an integer. This array is replaced during a strategic merge patch."
    }, 
    "key": {
      "type": "string", 
      "description": "The label key that the selector applies to."
    }
  }
}

=== instrumenta/kubernetes-json-schema/v1.8.9-local/podsecuritypolicyspec-extensions-v1beta1.json
{
  "description": "Pod Security Policy Spec defines the policy enforced.",
  "required": [
    "seLinux",
    "runAsUser",
    "supplementalGroups",
    "fsGroup"
  ],
  "properties": {
    "allowPrivilegeEscalation": {
      "description": "AllowPrivilegeEscalation determines if a pod can request to allow privilege escalation. If unspecified, defaults to true.",
      "type": "boolean"
    },
    "allowedCapabilities": {
      "description": "AllowedCapabilities is a list of capabilities that can be requested to add to the container. Capabilities in this field may be added at the pod author's discretion. You must not list a capability in both AllowedCapabilities and RequiredDropCapabilities.",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "allowedHostPaths": {
      "description": "is a white list of allowed host paths. Empty indicates that all host paths may be used.",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.api.extensions.v1beta1.AllowedHostPath"
      }
    },
    "defaultAddCapabilities": {
      "description": "DefaultAddCapabilities is the default set of capabilities that will be added to the container unless the pod spec specifically drops the capability.  You may not list a capabiility in both DefaultAddCapabilities and RequiredDropCapabilities.",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "defaultAllowPrivilegeEscalation": {
      "description": "DefaultAllowPrivilegeEscalation controls the default setting for whether a process can gain more privileges than its parent process.",
      "type": "boolean"
    },
    "fsGroup": {
      "description": "FSGroup is the strategy that will dictate what fs group is used by the SecurityContext.",
      "$ref": "_definitions.json#/definitions/io.k8s.api.extensions.v1beta1.FSGroupStrategyOptions"
    },
    "hostIPC": {
      "description": "hostIPC determines if the policy allows the use of HostIPC in the pod spec.",
      "type": "boolean"
    },
    "hostNetwork": {
      "description": "hostNetwork determines if the policy allows the use of HostNetwork in the pod spec.",
      "type": "boolean"
    },
    "hostPID": {
      "description": "hostPID determines if the policy allows the use of HostPID in the pod spec.",
      "type": "boolean"
    },
    "hostPorts": {
      "description": "hostPorts determines which host port ranges are allowed to be exposed.",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.api.extensions.v1beta1.HostPortRange"
      }
    },
    "privileged": {
      "description": "privileged determines if a pod can request to be run as privileged.",
      "type": "boolean"
    },
    "readOnlyRootFilesystem": {
      "description": "ReadOnlyRootFilesystem when set to true will force containers to run with a read only root file system.  If the container specifically requests to run with a non-read only root file system the PSP should deny the pod. If set to false the container may run with a read only root file system if it wishes but it will not be forced to.",
      "type": "boolean"
    },
    "requiredDropCapabilities": {
      "description": "RequiredDropCapabilities are the capabilities that will be dropped from the container.  These are required to be dropped and cannot be added.",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "runAsUser": {
      "description": "runAsUser is the strategy that will dictate the allowable RunAsUser values that may be set.",
      "$ref": "_definitions.json#/definitions/io.k8s.api.extensions.v1beta1.RunAsUserStrategyOptions"
    },
    "seLinux": {
      "description": "seLinux is the strategy that will dictate the allowable labels that may be set.",
      "$ref": "_definitions.json#/definitions/io.k8s.api.extensions.v1beta1.SELinuxStrategyOptions"
    },
    "supplementalGroups": {
      "description": "SupplementalGroups is the strategy that will dictate what supplemental groups are used by the SecurityContext.",
      "$ref": "_definitions.json#/definitions/io.k8s.api.extensions.v1beta1.SupplementalGroupsStrategyOptions"
    },
    "volumes": {
      "description": "volumes is a white list of allowed volume plugins.  Empty indicates that all plugins may be used.",
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": [
          "string",
          "null"
        ]
      }
    }
  },
  "$schema": "http://json-schema.org/schema#",
  "type": "object"
}
