=== instrumenta/kubernetes-json-schema/v1.10.11-local/jsonschemaprops.json
{
  "$schema": "http://json-schema.org/schema#", 
  "type": "object", 
  "description": "JSONSchemaProps is a JSON-Schema following Specification Draft 4 (http://json-schema.org/).", 
  "properties": {
    "minProperties": {
      "type": "integer", 
      "format": "int64"
    }, 
    "uniqueItems": {
      "type": "boolean"
    }, 
    "minimum": {
      "type": "number", 
      "format": "double"
    }, 
    "maxItems": {
      "type": "integer", 
      "format": "int64"
    }, 
    "$schema": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "anyOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "id": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "$ref": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "exclusiveMaximum": {
      "type": "boolean"
    }, 
    "title": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "exclusiveMinimum": {
      "type": "boolean"
    }, 
    "allOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "patternProperties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "multipleOf": {
      "type": "number", 
      "format": "double"
    }, 
    "maxProperties": {
      "type": "integer", 
      "format": "int64"
    }, 
    "type": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "description": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "format": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "minLength": {
      "type": "integer", 
      "format": "int64"
    }, 
    "enum": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "oneOf": {
      "items": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "dependencies": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrStringArray"
      }, 
      "type": "object"
    }, 
    "maxLength": {
      "type": "integer", 
      "format": "int64"
    }, 
    "not": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
    }, 
    "externalDocs": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.ExternalDocumentation"
    }, 
    "properties": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "additionalItems": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    }, 
    "default": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    }, 
    "items": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrArray"
    }, 
    "required": {
      "items": {
        "type": "string"
      }, 
      "type": [
        "array", 
        "null"
      ]
    }, 
    "maximum": {
      "type": "number", 
      "format": "double"
    }, 
    "minItems": {
      "type": "integer", 
      "format": "int64"
    }, 
    "pattern": {
      "type": [
        "string", 
        "null"
      ]
    }, 
    "additionalProperties": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaPropsOrBool"
    }, 
    "definitions": {
      "additionalProperties": {
        "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSONSchemaProps"
      }, 
      "type": "object"
    }, 
    "example": {
      "$ref": "_definitions.json#/definitions/io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1beta1.JSON"
    }
  }
}

=== instrumenta/kubernetes-json-schema/v1.16.7/jobspec-batch-v1.json
{
  "description": "JobSpec describes how the job execution will look like.",
  "properties": {
    "activeDeadlineSeconds": {
      "description": "Specifies the duration in seconds relative to the startTime that the job may be active before the system tries to terminate it; value must be positive integer",
      "format": "int64",
      "type": [
        "integer",
        "null"
      ]
    },
    "backoffLimit": {
      "description": "Specifies the number of retries before marking this job failed. Defaults to 6",
      "format": "int32",
      "type": [
        "integer",
        "null"
      ]
    },
    "completions": {
      "description": "Specifies the desired number of successfully finished pods the job should be run with.  Setting to nil means that the success of any pod signals the success of all pods, and allows parallelism to have any positive value.  Setting to 1 means that parallelism is limited to 1 and the success of that pod signals the success of the job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/",
      "format": "int32",
      "type": [
        "integer",
        "null"
      ]
    },
    "manualSelector": {
      "description": "manualSelector controls generation of pod labels and pod selectors. Leave `manualSelector` unset unless you are certain what you are doing. When false or unset, the system pick labels unique to this job and appends those labels to the pod template.  When true, the user is responsible for picking unique labels and specifying the selector.  Failure to pick a unique label may cause this and other jobs to not function correctly.  However, You may see `manualSelector=true` in jobs that were created with the old `extensions/v1beta1` API. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/#specifying-your-own-pod-selector",
      "type": [
        "boolean",
        "null"
      ]
    },
    "parallelism": {
      "description": "Specifies the maximum desired number of pods the job should run at any given time. The actual number of pods running in steady state will be less than this number when ((.spec.completions - .status.successful) < .spec.parallelism), i.e. when the work left to do is less than max parallelism. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/",
      "format": "int32",
      "type": [
        "integer",
        "null"
      ]
    },
    "selector": {
      "$ref": "https://kubernetesjsonschema.dev/v1.16.7/_definitions.json#/definitions/io.k8s.apimachinery.pkg.apis.meta.v1.LabelSelector",
      "description": "A label query over pods that should match the pod count. Normally, the system sets this field for you. More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors"
    },
    "template": {
      "$ref": "https://kubernetesjsonschema.dev/v1.16.7/_definitions.json#/definitions/io.k8s.api.core.v1.PodTemplateSpec",
      "description": "Describes the pod that will be created when executing a job. More info: https://kubernetes.io/docs/concepts/workloads/controllers/jobs-run-to-completion/"
    },
    "ttlSecondsAfterFinished": {
      "description": "ttlSecondsAfterFinished limits the lifetime of a Job that has finished execution (either Complete or Failed). If this field is set, ttlSecondsAfterFinished after the Job finishes, it is eligible to be automatically deleted. When the Job is being deleted, its lifecycle guarantees (e.g. finalizers) will be honored. If this field is unset, the Job won't be automatically deleted. If this field is set to zero, the Job becomes eligible to be deleted immediately after it finishes. This field is alpha-level and is only honored by servers that enable the TTLAfterFinished feature.",
      "format": "int32",
      "type": [
        "integer",
        "null"
      ]
    }
  },
  "required": [
    "template"
  ],
  "type": "object",
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/v1.13.4-standalone/csipersistentvolumesource.json
{
  "description": "Represents storage that is managed by an external CSI volume driver (Beta feature)",
  "required": [
    "driver",
    "volumeHandle"
  ],
  "properties": {
    "controllerPublishSecretRef": {
      "description": "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace",
      "properties": {
        "name": {
          "description": "Name is unique within a namespace to reference a secret resource.",
          "type": [
            "string",
            "null"
          ]
        },
        "namespace": {
          "description": "Namespace defines the space within which the secret name must be unique.",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "driver": {
      "description": "Driver is the name of the driver to use for this volume. Required.",
      "type": [
        "string",
        "null"
      ]
    },
    "fsType": {
      "description": "Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\".",
      "type": [
        "string",
        "null"
      ]
    },
    "nodePublishSecretRef": {
      "description": "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace",
      "properties": {
        "name": {
          "description": "Name is unique within a namespace to reference a secret resource.",
          "type": [
            "string",
            "null"
          ]
        },
        "namespace": {
          "description": "Namespace defines the space within which the secret name must be unique.",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "nodeStageSecretRef": {
      "description": "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace",
      "properties": {
        "name": {
          "description": "Name is unique within a namespace to reference a secret resource.",
          "type": [
            "string",
            "null"
          ]
        },
        "namespace": {
          "description": "Namespace defines the space within which the secret name must be unique.",
          "type": [
            "string",
            "null"
          ]
        }
      }
    },
    "readOnly": {
      "description": "Optional: The value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write).",
      "type": "boolean"
    },
    "volumeAttributes": {
      "description": "Attributes of the volume to publish.",
      "type": "object",
      "additionalProperties": {
        "type": [
          "string",
          "null"
        ]
      }
    },
    "volumeHandle": {
      "description": "VolumeHandle is the unique volume name returned by the CSI volume plugin\u2019s CreateVolume to refer to the volume on all subsequent calls. Required.",
      "type": [
        "string",
        "null"
      ]
    }
  },
  "$schema": "http://json-schema.org/schema#",
  "type": "object"
}

=== instrumenta/kubernetes-json-schema/v1.16.6-standalone-strict/topologyspreadconstraint-v1.json
{
  "description": "TopologySpreadConstraint specifies how to spread matching pods among the given topology.",
  "properties": {
    "labelSelector": {
      "description": "A label selector is a label query over a set of resources. The result of matchLabels and matchExpressions are ANDed. An empty label selector matches all objects. A null label selector matches no objects.",
      "properties": {
        "matchExpressions": {
          "description": "matchExpressions is a list of label selector requirements. The requirements are ANDed.",
          "items": {
            "description": "A label selector requirement is a selector that contains values, a key, and an operator that relates the key and values.",
            "properties": {
              "key": {
                "description": "key is the label key that the selector applies to.",
                "type": "string",
                "x-kubernetes-patch-merge-key": "key",
                "x-kubernetes-patch-strategy": "merge"
              },
              "operator": {
                "description": "operator represents a key's relationship to a set of values. Valid operators are In, NotIn, Exists and DoesNotExist.",
                "type": "string"
              },
              "values": {
                "description": "values is an array of string values. If the operator is In or NotIn, the values array must be non-empty. If the operator is Exists or DoesNotExist, the values array must be empty. This array is replaced during a strategic merge patch.",
                "items": {
                  "type": [
                    "string",
                    "null"
                  ]
                },
                "type": [
                  "array",
                  "null"
                ]
              }
            },
            "required": [
              "key",
              "operator"
            ],
            "type": [
              "object",
              "null"
            ],
            "additionalProperties": false
          },
          "type": [
            "array",
            "null"
          ]
        },
        "matchLabels": {
          "additionalProperties": {
            "type": [
              "string",
              "null"
            ]
          },
          "description": "matchLabels is a map of {key,value} pairs. A single {key,value} in the matchLabels map is equivalent to an element of matchExpressions, whose key field is \"key\", the operator is \"In\", and the values array contains only \"value\". The requirements are ANDed.",
          "type": [
            "object",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ],
      "additionalProperties": false
    },
    "maxSkew": {
      "description": "MaxSkew describes the degree to which pods may be unevenly distributed. It's the maximum permitted difference between the number of matching pods in any two topology domains of a given topology type. For example, in a 3-zone cluster, MaxSkew is set to 1, and pods with the same labelSelector spread as 1/1/0: | zone1 | zone2 | zone3 | |   P   |   P   |       | - if MaxSkew is 1, incoming pod can only be scheduled to zone3 to become 1/1/1; scheduling it onto zone1(zone2) would make the ActualSkew(2-0) on zone1(zone2) violate MaxSkew(1). - if MaxSkew is 2, incoming pod can be scheduled onto any zone. It's a required field. Default value is 1 and 0 is not allowed.",
      "format": "int32",
      "type": [
        "integer",
        "null"
      ]
    },
    "topologyKey": {
      "description": "TopologyKey is the key of node labels. Nodes that have a label with this key and identical values are considered to be in the same topology. We consider each <key, value> as a \"bucket\", and try to put balanced number of pods into each bucket. It's a required field.",
      "type": [
        "string",
        "null"
      ]
    },
    "whenUnsatisfiable": {
      "description": "WhenUnsatisfiable indicates how to deal with a pod if it doesn't satisfy the spread constraint. - DoNotSchedule (default) tells the scheduler not to schedule it - ScheduleAnyway tells the scheduler to still schedule it It's considered as \"Unsatisfiable\" if and only if placing incoming pod on any topology violates \"MaxSkew\". For example, in a 3-zone cluster, MaxSkew is set to 1, and pods with the same labelSelector spread as 3/1/1: | zone1 | zone2 | zone3 | | P P P |   P   |   P   | If WhenUnsatisfiable is set to DoNotSchedule, incoming pod can only be scheduled to zone2(zone3) to become 3/2/1(3/1/2) as ActualSkew(2-1) on zone2(zone3) satisfies MaxSkew(1). In other words, the cluster can still be imbalanced, but scheduler won't make it *more* imbalanced. It's a required field.",
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "maxSkew",
    "topologyKey",
    "whenUnsatisfiable"
  ],
  "type": "object",
  "additionalProperties": false,
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/master-standalone/csipersistentvolumesource.json
{
  "description": "Represents storage that is managed by an external CSI volume driver (Beta feature)",
  "properties": {
    "controllerExpandSecretRef": {
      "description": "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace",
      "properties": {
        "name": {
          "description": "Name is unique within a namespace to reference a secret resource.",
          "type": [
            "string",
            "null"
          ]
        },
        "namespace": {
          "description": "Namespace defines the space within which the secret name must be unique.",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "controllerPublishSecretRef": {
      "description": "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace",
      "properties": {
        "name": {
          "description": "Name is unique within a namespace to reference a secret resource.",
          "type": [
            "string",
            "null"
          ]
        },
        "namespace": {
          "description": "Namespace defines the space within which the secret name must be unique.",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "driver": {
      "description": "Driver is the name of the driver to use for this volume. Required.",
      "type": [
        "string",
        "null"
      ]
    },
    "fsType": {
      "description": "Filesystem type to mount. Must be a filesystem type supported by the host operating system. Ex. \"ext4\", \"xfs\", \"ntfs\".",
      "type": [
        "string",
        "null"
      ]
    },
    "nodePublishSecretRef": {
      "description": "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace",
      "properties": {
        "name": {
          "description": "Name is unique within a namespace to reference a secret resource.",
          "type": [
            "string",
            "null"
          ]
        },
        "namespace": {
          "description": "Namespace defines the space within which the secret name must be unique.",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "nodeStageSecretRef": {
      "description": "SecretReference represents a Secret Reference. It has enough information to retrieve secret in any namespace",
      "properties": {
        "name": {
          "description": "Name is unique within a namespace to reference a secret resource.",
          "type": [
            "string",
            "null"
          ]
        },
        "namespace": {
          "description": "Namespace defines the space within which the secret name must be unique.",
          "type": [
            "string",
            "null"
          ]
        }
      },
      "type": [
        "object",
        "null"
      ]
    },
    "readOnly": {
      "description": "Optional: The value to pass to ControllerPublishVolumeRequest. Defaults to false (read/write).",
      "type": [
        "boolean",
        "null"
      ]
    },
    "volumeAttributes": {
      "additionalProperties": {
        "type": [
          "string",
          "null"
        ]
      },
      "description": "Attributes of the volume to publish.",
      "type": [
        "object",
        "null"
      ]
    },
    "volumeHandle": {
      "description": "VolumeHandle is the unique volume name returned by the CSI volume plugin\u2019s CreateVolume to refer to the volume on all subsequent calls. Required.",
      "type": [
        "string",
        "null"
      ]
    }
  },
  "required": [
    "driver",
    "volumeHandle"
  ],
  "type": "object",
  "$schema": "http://json-schema.org/schema#"
}

=== instrumenta/kubernetes-json-schema/v1.10.11-standalone-strict/deploymentcondition-apps-v1beta1.json
{
  "additionalProperties": false, 
  "required": [
    "type", 
    "status"
  ], 
  "description": "DeploymentCondition describes the state of a deployment at a certain point.", 
  "properties": {
    "status": {
      "type": "string", 
      "description": "Status of the condition, one of True, False, Unknown."
    }, 
    "lastUpdateTime": {
      "type": "string", 
      "format": "date-time"
    }, 
    "lastTransitionTime": {
      "type": "string", 
      "format": "date-time"
    }, 
    "reason": {
      "type": "string", 
      "description": "The reason for the condition's last transition."
    }, 
    "message": {
      "type": "string", 
      "description": "A human readable message indicating details about the transition."
    }, 
    "type": {
      "type": "string", 
      "description": "Type of deployment condition."
    }
  }
}
